description: SSH Singularity

target:
  service: sing
  name: GenAI-Shared-UKSouth2
  workspace_name: Singularity-GenAI-WS-UKSouth2

environment:
  image: nvidia/pytorch:24.06-py3
  registry: nvcr.io
  setup:
    - pip list
    - echo 'Above is packages before launch cmd'
    - nvcc --version
    - echo "setup done"

code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: $CONFIG_DIR
  ignore:
  - my_long_corpus/*

storage:
  synthdatastore:
    storage_account_name: syntheticpipelinewus2
    container_name: datastore
    mount_dir: /mnt/synthdatastore
  outputsynth:
    storage_account_name: syntheticdatag6275770601
    container_name: azureml-blobstore-b4c46be1-7692-48a4-afd0-b6734d6c4b67
    mount_dir: /mnt/outputsynth

jobs:
- name: hello_world
  sla_tier: premium  # Default: premium
  execution_mode: basic  # Default: basic
  # sku: 40000000000G8
  sku: G8
  priority: high
  process_count_per_node: 1
  command:
    - echo "Hello World"
    - sleep infinity