description: submit omni_unified_v1_midtrain

target:
  service: sing
  # name:  aims-sing-a100-wus3
  name:  GenAI-Shared-UKSouth
  # name:  GenAI-Shared-UKSouth2
  workspace_name: synthetic-datagen-ws-wus3

environment:
  image: nvidia/pytorch:24.06-py3
  registry: nvcr.io
  setup:
  - echo "export PATH=$$PATH:$$HOME/.local/bin" >> ~/.bashrc && source ~/.bashrc
  - pip list
  - echo 'Above is packages before launch cmd'
  - nvcc --version
  - pip install gpustat
  - echo "setup done"

code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: $CONFIG_DIR

env_defaults:
  gpus: 8

storage:
  syntheticpipelinetrainerv1:
    storage_account_name: syntheticpipelinewus31
    container_name: genalign-mid-trainer-v1
    mount_dir: /mnt/syntheticpipelinetrainerv1

jobs:
- name: omni_unified_v1_midtrain_gpus${gpus}
  sla_tier: premium  # Default: premium
  execution_mode: basic  # Default: basic
  sku: 80G${gpus}
  priority: high
  process_count_per_node: 1
  command:
    - set -x
    - set -e
    - set -u
    - export PATH=$$HOME/.local/bin/:$$PATH
    - echo "===================="
    - echo $$AMLT_EXPERIMENT_NAME
    - echo "===================="
    # Launch the job.
    - bash ./scripts/run_00_driver_train.sh
  submit_args:
    env:
      { _AZUREML_SINGULARITY_JOB_UAI: /subscriptions/584bfbd1-d24e-4f7b-81cf-c953a75c45e5/resourcegroups/synthetic-dategen-RG/providers/Microsoft.ManagedIdentity/userAssignedIdentities/genAlign-umi }
  identity: managed